insert into products (product_name, department_name, price, stock_quantity)values("Coors Light", "food", "3","80");
insert into products (product_name, department_name, price, stock_quantity)values("Kraft Cheese", "food", "2","80");
insert into products (product_name, department_name, price, stock_quantity)values("48oz of Salmon", "food", "18","80");
insert into products (product_name, department_name, price, stock_quantity)values("TV", "Electronics", "500","5");
insert into products (product_name, department_name, price, stock_quantity)values("Hydro Flask", "other", "20","1000");
insert into products (product_name, department_name, price, stock_quantity)values("PS4", "Electronics", "300","20");
insert into products (product_name, department_name, price, stock_quantity)values("Kidney ", "food", "3","80");
insert into products (product_name, department_name, price, stock_quantity)values("Backpack", "clothing", "35","35");
insert into products (product_name, department_name, price, stock_quantity)values("G.I. Joe", "toys", "15","100");
insert into products (product_name, department_name, price, stock_quantity)values("6oz of Liquid Courage", "food", "500","1");
